// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN0yYyYLIewwuE8zNFIkv3qt1IJHbvFjo',
    appId: '1:1028534740072:web:a554e11b2ff2b43c5a87dd',
    messagingSenderId: '1028534740072',
    projectId: 'hockey-ac6b2',
    authDomain: 'hockey-ac6b2.firebaseapp.com',
    databaseURL: 'https://hockey-ac6b2-default-rtdb.firebaseio.com',
    storageBucket: 'hockey-ac6b2.firebasestorage.app',
    measurementId: 'G-81ME8HZ2JQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf9SWt2q1BWhC5KlxoWbe6yKMg8pWwgq4',
    appId: '1:1028534740072:android:290176ebf7d31e125a87dd',
    messagingSenderId: '1028534740072',
    projectId: 'hockey-ac6b2',
    databaseURL: 'https://hockey-ac6b2-default-rtdb.firebaseio.com',
    storageBucket: 'hockey-ac6b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-HMs1RdvvBXfQ0pZqM_AY5Vyw-Wyj4ZI',
    appId: '1:1028534740072:ios:921c59041ec0e3e75a87dd',
    messagingSenderId: '1028534740072',
    projectId: 'hockey-ac6b2',
    databaseURL: 'https://hockey-ac6b2-default-rtdb.firebaseio.com',
    storageBucket: 'hockey-ac6b2.firebasestorage.app',
    iosBundleId: 'com.example.hockeyUnion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-HMs1RdvvBXfQ0pZqM_AY5Vyw-Wyj4ZI',
    appId: '1:1028534740072:ios:921c59041ec0e3e75a87dd',
    messagingSenderId: '1028534740072',
    projectId: 'hockey-ac6b2',
    databaseURL: 'https://hockey-ac6b2-default-rtdb.firebaseio.com',
    storageBucket: 'hockey-ac6b2.firebasestorage.app',
    iosBundleId: 'com.example.hockeyUnion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN0yYyYLIewwuE8zNFIkv3qt1IJHbvFjo',
    appId: '1:1028534740072:web:c1bb311985edf6ed5a87dd',
    messagingSenderId: '1028534740072',
    projectId: 'hockey-ac6b2',
    authDomain: 'hockey-ac6b2.firebaseapp.com',
    databaseURL: 'https://hockey-ac6b2-default-rtdb.firebaseio.com',
    storageBucket: 'hockey-ac6b2.firebasestorage.app',
    measurementId: 'G-PGW6D9TYHM',
  );
}
